site_name: ARC Guide

nav:
    - Home: index.md
    - About: about.md
    - Contact: contact.md
    - Events: events.md
    - Recruitment: recruitment.md
    - RemoteRig Setup: remoterig.md
    
theme: material

copyright: Written by The Predecessors 2020