site_name: ARC Guide

nav:
    - Home: index.md
    - About: about.md
    - Contact: contact.md
    - Events: events.md
    - Recruitment: recruitment.md
    - RemoteRig Setup: remoterig.md
    - Roles and Offices: offices_roles.md
    - Online Accounts: accounts_services.md
    
theme: material

copyright: Written by The Predecessors 2020. Long live the Predecessors.